### ISSUE TITLE
Files/Classes missing in the documentation

### ISSUE THREAD

**Issue by neoacevedo** [yiisoft/yii2-apidoc#277]
This issue is related to https://github.com/yiisoft/yii2-apidoc/issues/162

I'm using yii2-apidoc to generate the API documentation for a Laravel project. All classes except only one are well documented. 

Under my project structure `app\Http\Controllers\Api` I have 4 classes under this namespace:

- ApplicationController
- ServiceController
- ClientController
- DriverController

Just this last one, **DriverController**, is missing from the documentation. The other namespaces are well rendered in the final documentation.

**Comment by samdark** [comment]
In order to fix it we need it reproduceable so we need a set of files and steps to re-create your situation. Would you please provide these?

**Comment by neoacevedo** [comment]
### What steps will reproduce the problem?
- Running command to generate the API Documentation for a Laravel project: php X:\yii2\vendor\bin\apidoc api .\app\ C:\Documents\trabajo\project\apidoc --interactive=0 --exclude="vendor" --page-title="My Project - Documentación"
### What's expected?
To genenrate the documentation for all the classes
### What do you get instead?
The documentation for all classes, except only one: appHttp\Controllers\Api\DriverController

### Additional info
Running the command, I get the error: ` Parse Error: Syntax error, unexpected ')' on line 4801FUNCTION on line 12`
| Q                  | A
|--------------------| ---
| Yii version        | 2.0.44
| Yii APIDoc version | 2.1.6
| PHP version        | ~7.4/8.0
| Operating system   | Windows 11/ openSUSE TW

**Comment by samdark** [comment]
We don't have your Laravel project so can't reproduce it.

**Comment by samdark** [comment]
I'm afraid that's not enough. We need a set of files (it could be not your private project but the same case you've put together) that we can reproduce the issue with.

**Comment by arogachev** [comment]
Also I recommend to try the latest version of yii2-apidoc (3.0.0).

**Comment by samdark** [comment]
Yes, trying 3.0.0 definitely worth it. @arogachev did a great job squashing very significant amount of bugs.

**Comment by neoacevedo** [comment]
[app.zip](https://github.com/yiisoft/yii2-apidoc/files/7951291/app.zip)

Updating yii2-apidoc to version 3.0 and trying to generate the documentation raises in `The Yii Framework 2.0 does not seem to be installed. Try running composer install.`.

**Comment by samdark** [comment]
Good. So the bug in question is fixed.

Now, additional issue about source path:

1. What were your paths previously?
2. What did you execute and from which directory previously?

**Comment by neoacevedo** [comment]
The yii2 basic app project is under my public_html in the Linux server (Network drive for my windows machine):

- public_html
-- yii2-basic-app
-- my-laravel-project

For laravel documentation I run inside _my-laravel-project_: `php Z:\yii2-basic-app\vendor\bin\apidoc api . C:\Users\User\Documents\laravel\apidoc --interactive=0 --exclude="vendor" --page-title="Laravel - Documentation"`. For yii2-basic-app I run `php .\vendor\bin\apidoc api . C:\Users\User\Documents\yii2\apidoc --interactive=0 --exclude="vendor" --page-title="Yii2 - Documentation"`.

My question is, once updated, these commands stopped to work in my Windows PC, not else in my Linux machine. I executed in Windows the composer update command to update all packages for my yii2 basic app waiting it solved the issue but I didn't get any success result.

**Comment by samdark** [comment]
@arogachev would you please take a look at this paths issue?

**Comment by arogachev** [comment]
Unfortunately, I can not reproduce your problem. Successfully generated API docs for your app only.

I created test repository for this issue - https://github.com/arogachev/yii2-apidoc-issue-277 What else should be adjusted in your opinion to reflect your case (except title, etc.)?

**Comment by arogachev** [comment]
If I understood correctly, the last error only occurs on Windows OS, right? Maybe something related to network drive... :thinking: 

Just in case, I updated the test repo to use "yii2-app-basic" and again, API docs were successfully generated. But I ran tests only on Linux, unfortunately, I can't test it on Windows right now.

Maybe I'm still missing something. A little bit more details about folder / file structure and setup on Windows would be useful.

**Comment by neoacevedo** [comment]
I have checked and, if I have yii2-apidoc in any Windows directory, I'm able to make the Api Documentation of any of my projects in the network drive, but if I try to run yii2-apidoc from a network drive, I get the mentioned error.

As I said, my projects are located in a Linux PC, and the folder is mapped in Windows as network drive, for instance, Z:, if I try to run yii2-apidoc from the Z: drive, I get the error while if I run yii2-apidoc from C: or D: (my Windows drives) it runs without problems.

**Comment by samdark** [comment]
@neoacevedo that looks like a very special edge case that is hard to reproduce. I'm closing the issue but if you'll find out what's wrong exectly, please submit a new one. Thanks.
